### ISSUE TITLE
Failed to activate the language-smarty package

### ISSUE THREAD

**Issue by hermanndettmann** [MaxGiting/atom-language-smarty#3] opened 2015-05-19 13:46 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [language-smarty](https://github.com/MaxGiting/atom-language-smarty) package, v1.0.0
### Stack Trace

Failed to activate the language-smarty package

```
At Cannot read property 'scopeName' of undefined

TypeError: Cannot read property 'scopeName' of undefined
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:124:30)
    at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1076:35)
    at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2224:33)
    at /Users/hermanndettmann/.atom/packages/language-smarty/index.coffee:8:25
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
    at Object.module.exports.activate (/Users/hermanndettmann/.atom/packages/language-smarty/index.coffee:6:29)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
```
### Commands

```
     -2:34.3.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -2:30.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:25.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:17.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:33.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:27.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:07.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:57.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:39.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:35.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:33.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.9.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:27 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
color-picker, v1.7.0
emmet, v2.3.9
language-smarty, v1.0.0

# Dev
No dev packages
```

**Comment by llagerlof** [comment] 2015-06-25 18:14
[Enter steps to reproduce below:]
1. Try to install the Smarty package in Atom 1.0
2. Boom!

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [language-smarty](https://github.com/MaxGiting/atom-language-smarty) package, v1.0.0

### Stack Trace

Failed to activate the language-smarty package

```
At Cannot read property 'scopeName' of undefined

TypeError: Cannot read property 'scopeName' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\tokenized-buffer.js:130:30)
  at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\display-buffer.js:1151:35)
  at TextEditor.module.exports.TextEditor.setGrammar (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\text-editor.js:2264:33)
  at C:\Users\lawrence\.atom\packages\language-smarty\index.coffee:6:20
  at Workspace.module.exports.Workspace.observeTextEditors (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\workspace.js:276:9)
  at Object.module.exports.activate (C:\Users\lawrence\.atom\packages\language-smarty\index.coffee:4:22)
  at Package.module.exports.Package.activateNow (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
  at C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.activate (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:452:21)
  at C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:362:29
  at exit (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\lawrence\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -3:57.1.0 core:delete (atom-text-editor.editor.mini.is-focused)
  2x -3:40.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:07.9.0 core:copy (atom-text-editor.editor.is-focused)
     -1:46.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
language-smarty, v1.0.0

# Dev
No dev packages
```

**Comment by MaxGiting** [comment] 2015-06-29 20:21
I've tried to install on a fresh atom installation on Mac OS X and have not been able to replicate this issue. Have you been able to install with an old fashioned turn it off turn it on? 

Strange :confused:

**Comment by llagerlof** [comment] 2015-06-29 21:00
I tested in Windows 8 x64. It's incompatible?

**Comment by MaxGiting** [comment] 2015-06-29 21:54
I just installed on a clean atom installation on a windows 8.1 setup. Annoyingly for this error it worked fine for me. Have you been able to get it working by doing a new atom installation and package install?

**Comment by llagerlof** [comment] 2015-06-30 12:51
Yes. I tried to unistall Atom and delete the .atom directory in my user directory. So I reinstall it, but same error, sorry. Very strange.
Looks like @hermanndettmann in this same thread is having the same problem, but with a previous version of Atom.

```
Failed to activate the language-smarty package

At Cannot read property 'scopeName' of undefined
```

**Comment by lmarcelocc** [comment] 2015-07-07 13:45
Hi,

same here at windows 7 x64.

**Comment by MaxGiting** [comment] 2015-07-07 17:55
I managed to reproduce the error and have updated the package to fix it. If any of you could please test that would be very helpful.

For anyone else trying to solve a similar issue I found help here.
https://github.com/wingyplus/language-robot-framework/issues/8

The package was trying to assign itself before it had been activated in index.coffee

**Closed as completed by MaxGiting** 2015-07-07 17:55 UTC

**Comment by llagerlof** [comment] 2015-07-07 19:37
Beautiful. Installed without any trouble and it's working perfectly. Thanks!

**Comment by timkelty** [comment] 2015-11-05 19:46
Getting this with the latest version installed: 
`Maximum call stack size exceeded`
1. Open Atom

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [language-smarty](https://github.com/MaxGiting/atom-language-smarty) package, v1.3.0

### Stack Trace

Failed to activate the language-smarty package

```
At Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at Object.module.exports.activate (/Users/timkelty/.atom/packages/language-smarty/index.coffee:3:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
    at Object.module.exports.activate (/Users/timkelty/.atom/packages/language-smarty/index.coffee:3:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:232:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:212:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:153:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:205:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:21)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "tomorrow-night-eighties-syntax"
    ],
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "linter-csslint"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-alignment, v0.12.1
docblockr, v0.7.3
editorconfig, v1.2.2
emmet, v2.3.14
file-type-icons, v0.7.3
file-types, v0.5.1
html-entities, v0.4.0
javascript-snippets, v1.0.0
js-autoimport, v0.5.1
language-apache, v1.3.0
language-ini, v1.14.0
language-nunjucks, v2.0.0
linter, v1.10.0
linter-js-yaml, v1.2.0
linter-jshint, v1.2.1
linter-php, v1.1.0
linter-tidy, v1.0.1
linter-xmllint, v0.0.7
markdown-preview-plus, v2.2.2
react, v0.12.10
set-syntax, v0.3.0
synced-sidebar, v0.4.2
tomorrow-night-eighties-syntax, v0.9.0

# Dev
No dev packages
```

**Comment by dryaner** [comment] 2015-11-16 07:45
1. Open Atom

**Atom Version**: 1.1.0
**System**: Windows 10
**Thrown From**: [language-smarty](https://github.com/MaxGiting/atom-language-smarty) package, v1.3.0

### Stack Trace

Failed to activate the language-smarty package

```
At Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at Promise.chain (native)
    at Promise.then (native)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:474:32)
    at Object.module.exports.activate (C:\Users\Haran\.atom\packages\atom-language-smarty\index.coffee:3:21)
    at Package.module.exports.Package.activateNow (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:232:19)
    at C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:212:32
    at Package.module.exports.Package.measure (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
    at C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:205:26
    at Package.module.exports.Package.activate (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:201:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package-manager.js:474:21)
    at Object.module.exports.activate (C:\Users\Haran\.atom\packages\atom-language-smarty\index.coffee:3:21)
    at Package.module.exports.Package.activateNow (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:232:19)
    at C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:212:32
    at Package.module.exports.Package.measure (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:153:15)
    at C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:205:26
    at Package.module.exports.Package.activate (C:\Users\Haran\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:201:34)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "about",
      "exception-reporting",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-less",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-yaml",
      "metrics",
      "open-on-github",
      "package-generator",
      "welcome",
      "git-plus",
      "git-history",
      "auto-indent"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".sun",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "useruploads2"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
color-picker, v2.0.13
docblockr, v0.7.3
editorconfig, v1.2.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.10.0
linter-csslint, v1.1.0
linter-jshint, v1.2.1
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
pigments, v0.18.1
pretty-json, v0.4.1
seti-ui, v0.8.1

# Dev
No dev packages
```
